version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/store-manager-fe
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu/store-manager-fe
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: afterDeploy.sh
          timeout: 2000
          runas: root