name: On Merge to Develop
on:
  pull_request:
    types: [closed]
    branches: 
    - 'develop'

jobs:
  deploy:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    steps:
      - name: Run your action
        run: echo "This job's status is ${{ job.status }}."

      - name: Checkout branch
        uses: actions/checkout@v3
      
      - name: Create project zip file
         run: zip -qq -r ./storeManager_fe.zip .

      - name: Install dependencies
        run: yarn build
      
      - name: Access to AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: 🚛 Upload to S3
         run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.S3_BUCKET_DIR_NAME }}/$GITHUB_SHA.zip
         
      - name: 🚀 Deploy to EC2 with CodeDeploy
         run: aws deploy create-deployment
             --application-name codedeploy-app
             --deployment-config-name CodeDeployDefault.AllAtOnce
             --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP_NAME }}
             --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=${{ secrets.S3_BUCKET_DIR_NAME }}/$GITHUB_SHA.zip